# Site Settings
baseurl: ""
url : "https://rindakim.github.io"

# Blog Settings
theme_settings :
  title : Rinda Kim tech blog
  favicon : :four_leaf_clover:
  # Profile Settings
  profile :
    image : assets/img/memoticon.png
    username : Rinda Kim
    description : Student studying computer science. specipically, AI and Data Analysis
    experience :
      - start : 2022-03-01
        end : 2022-03-08
        experience : Hanyang Univ ERICA, smart ICT
    skills : 
      - skill : Python
        value : 50  # Percent value
        
  # Icons
  icons :
    email:  darin5@hanyang.ac.kr
    linkedin:  # Full URL 
    github: RinDa525
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
