# Site Settings
baseurl: "https://RinDa525.github.io"
url : "https://rindakim.github.io"

# Blog Settings
theme_settings :
  title : simple blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Rinda Kim
    description : Student studying computer science. specipically, AI and Data Analysis
    experience :
      - start : 2021-03-01
        end : 2023-03-01
        experience : Hanyang Univ(ERICA), smart ICT
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  darin5@hanyang.ac.kr
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
